name: debug

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract metadata for the Docker image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/devops_cicd_final/shop_app_test
      - run: |
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outputs.labels }}"
          echo "${{ steps.meta }}"
          echo "${{ steps }}"


    # - name: Checkout
    #   uses: actions/checkout@v3

    # - name: Log into the Container registry
    #   uses: docker/login-action@v2
    #   with:
    #     registry: ghcr.io
    #     username: ${{ secrets.GHCR_USER }}
    #     password: ${{ secrets.GHCR_TOKEN }}

    # - name: Extract metadata for the Docker image
    #   id: meta
    #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
    #   with:
    #     images: ghcr.io/devops_cicd_final/shop_app_test

    # - name: debug
    #   run: |
    #     ls
    #     pwd

    # - name: Build and push the Docker image
    #   uses: docker/build-push-action@v3
    #   with:
    #     context: .
    #     push: true
    #     dockerfile: ./src/Dockerfile
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

  # treefourtree:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: little-core-labs/get-git-tag@v3.0.1
  #       id: tagName
  #       # with:
  #       #   tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
  #       #   tagRegexGroup: 1 # Optional. Default is 1.

  #     - name: output 
  #       run: |
  #         echo ${{ steps.tagName.outputs.tag }}
  #         echo ${{ steps.tagName.outputs }}
  #         echo ${{ steps.tagName }}

  #     - name: Some other step # Output usage example
  #       with:
  #         tagname: ${{ steps.tagName.outputs.tag }}


  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: DUMP github context
  #       env:
  #         GITHUB_CONTEXT: ${{ toJson(github) }}
  #       run: echo "$GITHUB_CONTEXT"

  # check-version:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0

  #     - uses: rickstaa/action-get-semver@v1
  #       id: get_semver
  #       with:
  #         bump_level: "minor"
  #     - name: Print current and next version
  #       run: |
  #         echo "Current version: ${{ steps.get_semver.outputs.current_version  }}"
  #         echo "Next version: ${{ steps.get_semver.outputs.next_version }}"

  # newone:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0

  #   - id: semver-tag
  #     uses: gandarez/semver-action@v1.0.1
  #   - name: "Created tag"
  #     run: echo "tag ${{ steps.semver-tag.outputs.semver_tag }}"

  # anotherone:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - uses: actions/checkout@v3

  #   - run: |
  #       git tag -l


  