name: linting with flake8

on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Lint with flake8 # stop the build if there are Python syntax errors or undefined names
      run: |
        flake8 shop_app --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 shop_app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics