name: Merge Request

on:
  pull_request:
    branch: [ main ]

jobs:

  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Unit-tests check + coverage
      run: |
        pytest --cov=shop_app ./tests/unit

  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:

    - name: Checkout for deploy
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: docker-compose up
      run: docker-compose -f tests/e2e/docker-compose.yml up -d

    - name: Wait 4 Selenium.
      run: sleep 4

    - name: Setup Database.
      run: |
        sudo apt update
        sudo apt install mysql-client-core-8.0
        mysql -h 127.0.0.1 -u username -ppassword example < "./sql/0000-create-table.sql"
        mysql -h 127.0.0.1 -u username -ppassword example < "./sql/0001-insert-data.sql"
        mysql -h 127.0.0.1 -u username -ppassword example < "./sql/0002-create-user.sql"



    - name: pytest e2e
      run: pytest ./tests/e2e/

    #- name: remove docker-compose
    #  run: docker-compose -f ./tests/e2e/docker-compose.yml rm -fsv
