name: STAGE - CI/CD Pipeline
on:
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install project
      run: |
        pip install -e . #Install a project in editable mode (i.e. setuptools “develop mode”) from a local project path or a VCS url.

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors
        flake8 shop_app --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. github editor is 127 chars wide (?)
        flake8 shop_app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.9]
      steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install project
      run: |
        pip install -e .

    - name: Test with pytest
      run: |
        pytest
